// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: products.proto

package com.example.protobuf;

public interface AnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Animal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>float weight = 2;</code>
   * @return The weight.
   */
  float getWeight();

  /**
   * <code>string origin = 3;</code>
   * @return The origin.
   */
  java.lang.String getOrigin();
  /**
   * <code>string origin = 3;</code>
   * @return The bytes for origin.
   */
  com.google.protobuf.ByteString
      getOriginBytes();

  /**
   * <code>repeated .Parts parts = 4;</code>
   */
  java.util.List<com.example.protobuf.Parts> 
      getPartsList();
  /**
   * <code>repeated .Parts parts = 4;</code>
   */
  com.example.protobuf.Parts getParts(int index);
  /**
   * <code>repeated .Parts parts = 4;</code>
   */
  int getPartsCount();
  /**
   * <code>repeated .Parts parts = 4;</code>
   */
  java.util.List<? extends com.example.protobuf.PartsOrBuilder> 
      getPartsOrBuilderList();
  /**
   * <code>repeated .Parts parts = 4;</code>
   */
  com.example.protobuf.PartsOrBuilder getPartsOrBuilder(
      int index);

  /**
   * <code>int64 day = 5;</code>
   * @return The day.
   */
  long getDay();

  /**
   * <code>int64 month = 6;</code>
   * @return The month.
   */
  long getMonth();

  /**
   * <code>int64 year = 7;</code>
   * @return The year.
   */
  long getYear();
}
