// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: products.proto

package com.example.protobuf;

/**
 * Protobuf type {@code Animal}
 */
public final class Animal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Animal)
    AnimalOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Animal.newBuilder() to construct.
  private Animal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Animal() {
    origin_ = "";
    parts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Animal();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Animal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 21: {

            weight_ = input.readFloat();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            origin_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              parts_ = new java.util.ArrayList<com.example.protobuf.Parts>();
              mutable_bitField0_ |= 0x00000001;
            }
            parts_.add(
                input.readMessage(com.example.protobuf.Parts.parser(), extensionRegistry));
            break;
          }
          case 40: {

            day_ = input.readInt64();
            break;
          }
          case 48: {

            month_ = input.readInt64();
            break;
          }
          case 56: {

            year_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        parts_ = java.util.Collections.unmodifiableList(parts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.protobuf.Products.internal_static_Animal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.protobuf.Products.internal_static_Animal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.protobuf.Animal.class, com.example.protobuf.Animal.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int WEIGHT_FIELD_NUMBER = 2;
  private float weight_;
  /**
   * <code>float weight = 2;</code>
   * @return The weight.
   */
  @java.lang.Override
  public float getWeight() {
    return weight_;
  }

  public static final int ORIGIN_FIELD_NUMBER = 3;
  private volatile java.lang.Object origin_;
  /**
   * <code>string origin = 3;</code>
   * @return The origin.
   */
  @java.lang.Override
  public java.lang.String getOrigin() {
    java.lang.Object ref = origin_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      origin_ = s;
      return s;
    }
  }
  /**
   * <code>string origin = 3;</code>
   * @return The bytes for origin.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginBytes() {
    java.lang.Object ref = origin_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      origin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTS_FIELD_NUMBER = 4;
  private java.util.List<com.example.protobuf.Parts> parts_;
  /**
   * <code>repeated .Parts parts = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.protobuf.Parts> getPartsList() {
    return parts_;
  }
  /**
   * <code>repeated .Parts parts = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.protobuf.PartsOrBuilder> 
      getPartsOrBuilderList() {
    return parts_;
  }
  /**
   * <code>repeated .Parts parts = 4;</code>
   */
  @java.lang.Override
  public int getPartsCount() {
    return parts_.size();
  }
  /**
   * <code>repeated .Parts parts = 4;</code>
   */
  @java.lang.Override
  public com.example.protobuf.Parts getParts(int index) {
    return parts_.get(index);
  }
  /**
   * <code>repeated .Parts parts = 4;</code>
   */
  @java.lang.Override
  public com.example.protobuf.PartsOrBuilder getPartsOrBuilder(
      int index) {
    return parts_.get(index);
  }

  public static final int DAY_FIELD_NUMBER = 5;
  private long day_;
  /**
   * <code>int64 day = 5;</code>
   * @return The day.
   */
  @java.lang.Override
  public long getDay() {
    return day_;
  }

  public static final int MONTH_FIELD_NUMBER = 6;
  private long month_;
  /**
   * <code>int64 month = 6;</code>
   * @return The month.
   */
  @java.lang.Override
  public long getMonth() {
    return month_;
  }

  public static final int YEAR_FIELD_NUMBER = 7;
  private long year_;
  /**
   * <code>int64 year = 7;</code>
   * @return The year.
   */
  @java.lang.Override
  public long getYear() {
    return year_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (java.lang.Float.floatToRawIntBits(weight_) != 0) {
      output.writeFloat(2, weight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(origin_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, origin_);
    }
    for (int i = 0; i < parts_.size(); i++) {
      output.writeMessage(4, parts_.get(i));
    }
    if (day_ != 0L) {
      output.writeInt64(5, day_);
    }
    if (month_ != 0L) {
      output.writeInt64(6, month_);
    }
    if (year_ != 0L) {
      output.writeInt64(7, year_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (java.lang.Float.floatToRawIntBits(weight_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, weight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(origin_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, origin_);
    }
    for (int i = 0; i < parts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, parts_.get(i));
    }
    if (day_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, day_);
    }
    if (month_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, month_);
    }
    if (year_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, year_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.protobuf.Animal)) {
      return super.equals(obj);
    }
    com.example.protobuf.Animal other = (com.example.protobuf.Animal) obj;

    if (getId()
        != other.getId()) return false;
    if (java.lang.Float.floatToIntBits(getWeight())
        != java.lang.Float.floatToIntBits(
            other.getWeight())) return false;
    if (!getOrigin()
        .equals(other.getOrigin())) return false;
    if (!getPartsList()
        .equals(other.getPartsList())) return false;
    if (getDay()
        != other.getDay()) return false;
    if (getMonth()
        != other.getMonth()) return false;
    if (getYear()
        != other.getYear()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getWeight());
    hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
    hash = (53 * hash) + getOrigin().hashCode();
    if (getPartsCount() > 0) {
      hash = (37 * hash) + PARTS_FIELD_NUMBER;
      hash = (53 * hash) + getPartsList().hashCode();
    }
    hash = (37 * hash) + DAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDay());
    hash = (37 * hash) + MONTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMonth());
    hash = (37 * hash) + YEAR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getYear());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.protobuf.Animal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protobuf.Animal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protobuf.Animal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protobuf.Animal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protobuf.Animal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protobuf.Animal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protobuf.Animal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.protobuf.Animal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.protobuf.Animal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.protobuf.Animal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.protobuf.Animal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.protobuf.Animal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.protobuf.Animal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Animal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Animal)
      com.example.protobuf.AnimalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobuf.Products.internal_static_Animal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobuf.Products.internal_static_Animal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobuf.Animal.class, com.example.protobuf.Animal.Builder.class);
    }

    // Construct using com.example.protobuf.Animal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPartsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      weight_ = 0F;

      origin_ = "";

      if (partsBuilder_ == null) {
        parts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        partsBuilder_.clear();
      }
      day_ = 0L;

      month_ = 0L;

      year_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.protobuf.Products.internal_static_Animal_descriptor;
    }

    @java.lang.Override
    public com.example.protobuf.Animal getDefaultInstanceForType() {
      return com.example.protobuf.Animal.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.protobuf.Animal build() {
      com.example.protobuf.Animal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.protobuf.Animal buildPartial() {
      com.example.protobuf.Animal result = new com.example.protobuf.Animal(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.weight_ = weight_;
      result.origin_ = origin_;
      if (partsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          parts_ = java.util.Collections.unmodifiableList(parts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.parts_ = parts_;
      } else {
        result.parts_ = partsBuilder_.build();
      }
      result.day_ = day_;
      result.month_ = month_;
      result.year_ = year_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.protobuf.Animal) {
        return mergeFrom((com.example.protobuf.Animal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.protobuf.Animal other) {
      if (other == com.example.protobuf.Animal.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getWeight() != 0F) {
        setWeight(other.getWeight());
      }
      if (!other.getOrigin().isEmpty()) {
        origin_ = other.origin_;
        onChanged();
      }
      if (partsBuilder_ == null) {
        if (!other.parts_.isEmpty()) {
          if (parts_.isEmpty()) {
            parts_ = other.parts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePartsIsMutable();
            parts_.addAll(other.parts_);
          }
          onChanged();
        }
      } else {
        if (!other.parts_.isEmpty()) {
          if (partsBuilder_.isEmpty()) {
            partsBuilder_.dispose();
            partsBuilder_ = null;
            parts_ = other.parts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            partsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPartsFieldBuilder() : null;
          } else {
            partsBuilder_.addAllMessages(other.parts_);
          }
        }
      }
      if (other.getDay() != 0L) {
        setDay(other.getDay());
      }
      if (other.getMonth() != 0L) {
        setMonth(other.getMonth());
      }
      if (other.getYear() != 0L) {
        setYear(other.getYear());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.protobuf.Animal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.protobuf.Animal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private float weight_ ;
    /**
     * <code>float weight = 2;</code>
     * @return The weight.
     */
    @java.lang.Override
    public float getWeight() {
      return weight_;
    }
    /**
     * <code>float weight = 2;</code>
     * @param value The weight to set.
     * @return This builder for chaining.
     */
    public Builder setWeight(float value) {
      
      weight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float weight = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeight() {
      
      weight_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object origin_ = "";
    /**
     * <code>string origin = 3;</code>
     * @return The origin.
     */
    public java.lang.String getOrigin() {
      java.lang.Object ref = origin_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        origin_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string origin = 3;</code>
     * @return The bytes for origin.
     */
    public com.google.protobuf.ByteString
        getOriginBytes() {
      java.lang.Object ref = origin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        origin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string origin = 3;</code>
     * @param value The origin to set.
     * @return This builder for chaining.
     */
    public Builder setOrigin(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      origin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string origin = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrigin() {
      
      origin_ = getDefaultInstance().getOrigin();
      onChanged();
      return this;
    }
    /**
     * <code>string origin = 3;</code>
     * @param value The bytes for origin to set.
     * @return This builder for chaining.
     */
    public Builder setOriginBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      origin_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.example.protobuf.Parts> parts_ =
      java.util.Collections.emptyList();
    private void ensurePartsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        parts_ = new java.util.ArrayList<com.example.protobuf.Parts>(parts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.protobuf.Parts, com.example.protobuf.Parts.Builder, com.example.protobuf.PartsOrBuilder> partsBuilder_;

    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public java.util.List<com.example.protobuf.Parts> getPartsList() {
      if (partsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(parts_);
      } else {
        return partsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public int getPartsCount() {
      if (partsBuilder_ == null) {
        return parts_.size();
      } else {
        return partsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public com.example.protobuf.Parts getParts(int index) {
      if (partsBuilder_ == null) {
        return parts_.get(index);
      } else {
        return partsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public Builder setParts(
        int index, com.example.protobuf.Parts value) {
      if (partsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartsIsMutable();
        parts_.set(index, value);
        onChanged();
      } else {
        partsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public Builder setParts(
        int index, com.example.protobuf.Parts.Builder builderForValue) {
      if (partsBuilder_ == null) {
        ensurePartsIsMutable();
        parts_.set(index, builderForValue.build());
        onChanged();
      } else {
        partsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public Builder addParts(com.example.protobuf.Parts value) {
      if (partsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartsIsMutable();
        parts_.add(value);
        onChanged();
      } else {
        partsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public Builder addParts(
        int index, com.example.protobuf.Parts value) {
      if (partsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartsIsMutable();
        parts_.add(index, value);
        onChanged();
      } else {
        partsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public Builder addParts(
        com.example.protobuf.Parts.Builder builderForValue) {
      if (partsBuilder_ == null) {
        ensurePartsIsMutable();
        parts_.add(builderForValue.build());
        onChanged();
      } else {
        partsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public Builder addParts(
        int index, com.example.protobuf.Parts.Builder builderForValue) {
      if (partsBuilder_ == null) {
        ensurePartsIsMutable();
        parts_.add(index, builderForValue.build());
        onChanged();
      } else {
        partsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public Builder addAllParts(
        java.lang.Iterable<? extends com.example.protobuf.Parts> values) {
      if (partsBuilder_ == null) {
        ensurePartsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parts_);
        onChanged();
      } else {
        partsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public Builder clearParts() {
      if (partsBuilder_ == null) {
        parts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        partsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public Builder removeParts(int index) {
      if (partsBuilder_ == null) {
        ensurePartsIsMutable();
        parts_.remove(index);
        onChanged();
      } else {
        partsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public com.example.protobuf.Parts.Builder getPartsBuilder(
        int index) {
      return getPartsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public com.example.protobuf.PartsOrBuilder getPartsOrBuilder(
        int index) {
      if (partsBuilder_ == null) {
        return parts_.get(index);  } else {
        return partsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public java.util.List<? extends com.example.protobuf.PartsOrBuilder> 
         getPartsOrBuilderList() {
      if (partsBuilder_ != null) {
        return partsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(parts_);
      }
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public com.example.protobuf.Parts.Builder addPartsBuilder() {
      return getPartsFieldBuilder().addBuilder(
          com.example.protobuf.Parts.getDefaultInstance());
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public com.example.protobuf.Parts.Builder addPartsBuilder(
        int index) {
      return getPartsFieldBuilder().addBuilder(
          index, com.example.protobuf.Parts.getDefaultInstance());
    }
    /**
     * <code>repeated .Parts parts = 4;</code>
     */
    public java.util.List<com.example.protobuf.Parts.Builder> 
         getPartsBuilderList() {
      return getPartsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.protobuf.Parts, com.example.protobuf.Parts.Builder, com.example.protobuf.PartsOrBuilder> 
        getPartsFieldBuilder() {
      if (partsBuilder_ == null) {
        partsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.protobuf.Parts, com.example.protobuf.Parts.Builder, com.example.protobuf.PartsOrBuilder>(
                parts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        parts_ = null;
      }
      return partsBuilder_;
    }

    private long day_ ;
    /**
     * <code>int64 day = 5;</code>
     * @return The day.
     */
    @java.lang.Override
    public long getDay() {
      return day_;
    }
    /**
     * <code>int64 day = 5;</code>
     * @param value The day to set.
     * @return This builder for chaining.
     */
    public Builder setDay(long value) {
      
      day_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 day = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDay() {
      
      day_ = 0L;
      onChanged();
      return this;
    }

    private long month_ ;
    /**
     * <code>int64 month = 6;</code>
     * @return The month.
     */
    @java.lang.Override
    public long getMonth() {
      return month_;
    }
    /**
     * <code>int64 month = 6;</code>
     * @param value The month to set.
     * @return This builder for chaining.
     */
    public Builder setMonth(long value) {
      
      month_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 month = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMonth() {
      
      month_ = 0L;
      onChanged();
      return this;
    }

    private long year_ ;
    /**
     * <code>int64 year = 7;</code>
     * @return The year.
     */
    @java.lang.Override
    public long getYear() {
      return year_;
    }
    /**
     * <code>int64 year = 7;</code>
     * @param value The year to set.
     * @return This builder for chaining.
     */
    public Builder setYear(long value) {
      
      year_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 year = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearYear() {
      
      year_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Animal)
  }

  // @@protoc_insertion_point(class_scope:Animal)
  private static final com.example.protobuf.Animal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.protobuf.Animal();
  }

  public static com.example.protobuf.Animal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Animal>
      PARSER = new com.google.protobuf.AbstractParser<Animal>() {
    @java.lang.Override
    public Animal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Animal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Animal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Animal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.protobuf.Animal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

