// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: products.proto

package com.example.protobuf;

public interface getAnimalsInProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getAnimalsInProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Animal animals = 1;</code>
   */
  java.util.List<com.example.protobuf.Animal> 
      getAnimalsList();
  /**
   * <code>repeated .Animal animals = 1;</code>
   */
  com.example.protobuf.Animal getAnimals(int index);
  /**
   * <code>repeated .Animal animals = 1;</code>
   */
  int getAnimalsCount();
  /**
   * <code>repeated .Animal animals = 1;</code>
   */
  java.util.List<? extends com.example.protobuf.AnimalOrBuilder> 
      getAnimalsOrBuilderList();
  /**
   * <code>repeated .Animal animals = 1;</code>
   */
  com.example.protobuf.AnimalOrBuilder getAnimalsOrBuilder(
      int index);
}
