// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: products.proto

package com.example.protobuf;

public interface getProductsWithAnimalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getProductsWithAnimalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Product products = 1;</code>
   */
  java.util.List<com.example.protobuf.Product> 
      getProductsList();
  /**
   * <code>repeated .Product products = 1;</code>
   */
  com.example.protobuf.Product getProducts(int index);
  /**
   * <code>repeated .Product products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .Product products = 1;</code>
   */
  java.util.List<? extends com.example.protobuf.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .Product products = 1;</code>
   */
  com.example.protobuf.ProductOrBuilder getProductsOrBuilder(
      int index);
}
