// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: products.proto

package com.example.protobuf;

public final class Products {
  private Products() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getAnimalsInProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getAnimalsInProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getAnimalsInProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getAnimalsInProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getProductsWithAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getProductsWithAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getProductsWithAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getProductsWithAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Animal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Animal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Parts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Parts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016products.proto\"(\n\032getAnimalsInProductR" +
      "equest\022\n\n\002id\030\001 \001(\003\"7\n\033getAnimalsInProduc" +
      "tResponse\022\030\n\007animals\030\001 \003(\0132\007.Animal\"*\n\034g" +
      "etProductsWithAnimalRequest\022\n\n\002id\030\001 \001(\003\"" +
      ";\n\035getProductsWithAnimalResponse\022\032\n\010prod" +
      "ucts\030\001 \003(\0132\010.Product\"u\n\006Animal\022\n\n\002id\030\001 \001" +
      "(\003\022\016\n\006weight\030\002 \001(\002\022\016\n\006origin\030\003 \001(\t\022\025\n\005pa" +
      "rts\030\004 \003(\0132\006.Parts\022\013\n\003day\030\005 \001(\003\022\r\n\005month\030" +
      "\006 \001(\003\022\014\n\004year\030\007 \001(\003\"8\n\005Parts\022\n\n\002id\030\001 \001(\003" +
      "\022\020\n\010partType\030\002 \001(\t\022\021\n\treference\030\003 \001(\003\",\n" +
      "\007Product\022\n\n\002id\030\001 \001(\003\022\025\n\005parts\030\002 \003(\0132\006.Pa" +
      "rts2\272\001\n\016ProductService\022P\n\023getAnimalsInPr" +
      "oduct\022\033.getAnimalsInProductRequest\032\034.get" +
      "AnimalsInProductResponse\022V\n\025getProductsW" +
      "ithAnimal\022\035.getProductsWithAnimalRequest" +
      "\032\036.getProductsWithAnimalResponseB\030\n\024com." +
      "example.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_getAnimalsInProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_getAnimalsInProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getAnimalsInProductRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_getAnimalsInProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_getAnimalsInProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getAnimalsInProductResponse_descriptor,
        new java.lang.String[] { "Animals", });
    internal_static_getProductsWithAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_getProductsWithAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getProductsWithAnimalRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_getProductsWithAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_getProductsWithAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getProductsWithAnimalResponse_descriptor,
        new java.lang.String[] { "Products", });
    internal_static_Animal_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Animal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Animal_descriptor,
        new java.lang.String[] { "Id", "Weight", "Origin", "Parts", "Day", "Month", "Year", });
    internal_static_Parts_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Parts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Parts_descriptor,
        new java.lang.String[] { "Id", "PartType", "Reference", });
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_descriptor,
        new java.lang.String[] { "Id", "Parts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
